services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch_pegman
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic-network

  cerebro:
    image: lmenezes/cerebro:0.9.4
    container_name: cerebro_pegman
    ports:
      - "9000:9000"
    environment:
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana_pegman
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

  nginx:
    image: nginx:latest
    container_name: nginx_pegman
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elastic-network

volumes:
  es_data:
    driver: local

networks:
  elastic-network:
    driver: bridge